In [70]:
# Import thư viện
import pandas as pd
import numpy as np

In [71]:
# Đọc dữ liệu CSV
df = pd.read_csv("../data/raw/xau_usd_historical_data.csv")
df.head()

         Date     Price      Open      High       Low Vol. Change %
0  2026/04/08  4,762.18  4,835.42  4,856.00  4,733.10  NaN   -1.48%
1  2026/04/07  4,833.63  4,660.00  4,835.95  4,607.30  NaN    3.93%
2  2026/04/06  4,650.89  4,653.83  4,706.67  4,601.08  NaN    0.87%
3  2026/04/05  4,610.62  4,648.31  4,670.74  4,605.25  NaN   -1.41%
4  2026/04/03  4,676.42  4,676.42  4,676.42  4,676.42  NaN    0.00%

In [72]:
# Kiểm tra thông tin dữ liệu
print("Shape:", df.shape)
print("\nColumns:", df.columns.tolist())
print("\nInfo:")
print(df.info())

Shape: (784, 7)

Columns: ['Date', 'Price', 'Open', 'High', 'Low', 'Vol.', 'Change %']

Info:
<class 'pandas.DataFrame'>
RangeIndex: 784 entries, 0 to 783
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Date      784 non-null    str
 1   Price     784 non-null    str
 2   Open      784 non-null    str
 3   High      784 non-null    str
 4   Low       784 non-null    str
 5   Vol.      14 non-null     str
 6   Change %  784 non-null    str
dtypes: str(7)
memory usage: 43.0 KB
None

In [73]:
# Đổi tên cột về chuẩn
df = df.rename(columns={
    "Date": "date",
    "Price": "close",
    "Open": "open",
    "High": "high",
    "Low": "low",
    "Vol.": "volume",
    "Change %": "change_pct"
})
df.head()

         date     close      open      high       low volume change_pct
0  2026/04/08  4,762.18  4,835.42  4,856.00  4,733.10    NaN     -1.48%
1  2026/04/07  4,833.63  4,660.00  4,835.95  4,607.30    NaN      3.93%
2  2026/04/06  4,650.89  4,653.83  4,706.67  4,601.08    NaN      0.87%
3  2026/04/05  4,610.62  4,648.31  4,670.74  4,605.25    NaN     -1.41%
4  2026/04/03  4,676.42  4,676.42  4,676.42  4,676.42    NaN      0.00%

In [74]:
# Chuyển cột date về kiểu datetime
df["date"] = pd.to_datetime(df["date"], format="%Y/%m/%d")
df[["date"]].head()

        date
0 2026-04-08
1 2026-04-07
2 2026-04-06
3 2026-04-05
4 2026-04-03

In [75]:
# Chuyển các cột giá về kiểu số thực
price_cols = ["close", "open", "high", "low"]

for col in price_cols:
    df[col] = df[col].astype(str).str.replace(",", "", regex=False)
    df[col] = pd.to_numeric(df[col], errors="coerce")

df[price_cols].head()

     close     open     high      low
0  4762.18  4835.42  4856.00  4733.10
1  4833.63  4660.00  4835.95  4607.30
2  4650.89  4653.83  4706.67  4601.08
3  4610.62  4648.31  4670.74  4605.25
4  4676.42  4676.42  4676.42  4676.42

In [76]:
# Chuyển cột change_pct về kiểu float

df["change_pct"] = (
    df["change_pct"]
    .astype(str)
    .str.strip()                       # bỏ khoảng trắng đầu cuối
    .str.replace('"', '', regex=False) # bỏ dấu nháy kép
    .str.replace("%", "", regex=False) # bỏ dấu %
    .str.replace("−", "-", regex=False) # nếu có dấu âm unicode
)

df["change_pct"] = pd.to_numeric(df["change_pct"], errors="coerce") / 100
df[["change_pct"]].head()

   change_pct
0     -0.0148
1      0.0393
2      0.0087
3     -0.0141
4      0.0000

In [77]:
# Xem lại thông tin dữ liệu sau khi đã chuyển đổi kiểu dữ liệu
print("\nInfo after type conversion:")
print(df.info())
df.head()

Info after type conversion:
<class 'pandas.DataFrame'>
RangeIndex: 784 entries, 0 to 783
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        784 non-null    datetime64[us]
 1   close       784 non-null    float64
 2   open        784 non-null    float64
 3   high        784 non-null    float64
 4   low         784 non-null    float64
 5   volume      14 non-null     str
 6   change_pct  784 non-null    float64
dtypes: datetime64[us](1), float64(5), str(1)
memory usage: 43.0 KB
None

        date    close     open     high      low volume  change_pct
0 2026-04-08  4762.18  4835.42  4856.00  4733.10    NaN     -0.0148
1 2026-04-07  4833.63  4660.00  4835.95  4607.30    NaN      0.0393
2 2026-04-06  4650.89  4653.83  4706.67  4601.08    NaN      0.0087
3 2026-04-05  4610.62  4648.31  4670.74  4605.25    NaN     -0.0141
4 2026-04-03  4676.42  4676.42  4676.42  4676.42    NaN      0.0000

In [78]:
# Sắp xếp dữ liệu theo ngày tăng dần

df = df.sort_values("date").reset_index(drop=True)
df.head(), df.tail()

(        date    close     open     high      low volume  change_pct
 0 2023-04-03  1984.11  1970.84  1990.64  1949.82    NaN      0.0082
 1 2023-04-04  2019.97  1984.59  2025.19  1977.01    NaN      0.0181
 2 2023-04-05  2020.35  2020.44  2032.20  2009.99    NaN      0.0002
 3 2023-04-06  2008.02  2020.13  2021.63  2000.88    NaN     -0.0061
 4 2023-04-10  1989.95  2008.30  2011.17  1981.59    NaN     -0.0090,
           date    close     open     high      low volume  change_pct
 779 2026-04-03  4676.42  4676.42  4676.42  4676.42    NaN      0.0000
 780 2026-04-05  4610.62  4648.31  4670.74  4605.25    NaN     -0.0141
 781 2026-04-06  4650.89  4653.83  4706.67  4601.08    NaN      0.0087
 782 2026-04-07  4833.63  4660.00  4835.95  4607.30    NaN      0.0393
 783 2026-04-08  4762.18  4835.42  4856.00  4733.10    NaN     -0.0148)

In [79]:
# Kiểm tra ngày bị trùng lặp

duplicate_dates = df["date"].duplicated().sum()
print("Số ngày bị trùng:", duplicate_dates)

# df[df["date"].duplicated(keep=False)].sort_values("date") Nếu muốn xem cụ thể các ngày bị trùng
# Xử lý ngày bị trùng (nếu có) bằng cách giữ lại bản ghi đầu tiên và loại bỏ các bản ghi trùng lặp khác
if duplicate_dates > 0:
    df = df.drop_duplicates(subset=["date"]).reset_index(drop=True)

Số ngày bị trùng: 0

In [80]:
# Kiểm tra missing values
df.isnull().sum()

date            0
close           0
open            0
high            0
low             0
volume        770
change_pct      0
dtype: int64

In [81]:
# Kiểm tra logic OHLC

invalid_ohlc = df[
    (df["high"] < df["open"]) |
    (df["high"] < df["close"]) |
    (df["low"] > df["open"]) |
    (df["low"] > df["close"]) |
    (df["high"] < df["low"])
]

print("Số dòng OHLC bất thường:", len(invalid_ohlc))
invalid_ohlc.head()

# Nếu Số dòng OHLC bất thường = 0 thì dữ liệu đã sạch về mặt logic OHLC, nếu có thể xem chi tiết các dòng bất thường để xử lý nếu cần thiết

Số dòng OHLC bất thường: 7

          date    close     open     high      low volume  change_pct
43  2023-06-02  1947.63  1978.14  1983.52  1947.67    NaN     -0.0153
46  2023-06-07  1939.63  1963.59  1970.26  1939.80    NaN     -0.0118
186 2023-12-20  2029.19  2040.34  2043.94  2029.37    NaN     -0.0054
192 2023-12-28  2064.86  2077.34  2088.54  2065.89    NaN     -0.0059
345 2024-07-31  2448.10  2410.09  2451.00  2410.17    NaN      0.0165

In [82]:
# Giữ lại các cột cần thiết cho việc dự báo giá vàng
df_clean = df[["date", "open", "high", "low", "close"]].copy()
df_clean.head()

        date     open     high      low    close
0 2023-04-03  1970.84  1990.64  1949.82  1984.11
1 2023-04-04  1984.59  2025.19  1977.01  2019.97
2 2023-04-05  2020.44  2032.20  2009.99  2020.35
3 2023-04-06  2020.13  2021.63  2000.88  2008.02
4 2023-04-10  2008.30  2011.17  1981.59  1989.95

In [ ]:
# Kiểm tra lại type dữ liệu trước khi lưu file
print(df_clean.dtypes)
print(df_clean.head())

date     datetime64[us]
open            float64
high            float64
low             float64
close           float64
dtype: object
        date     open     high      low    close
0 2023-04-03  1970.84  1990.64  1949.82  1984.11
1 2023-04-04  1984.59  2025.19  1977.01  2019.97
2 2023-04-05  2020.44  2032.20  2009.99  2020.35
3 2023-04-06  2020.13  2021.63  2000.88  2008.02
4 2023-04-10  2008.30  2011.17  1981.59  1989.95

In [84]:
# Lưu dữ liệu đã làm sạch vào file mới
df_clean.to_csv("../data/processed/gold_cleaned.csv", index=False)
print("Đã lưu file: ../data/processed/gold_cleaned.csv")

Đã lưu file: ../data/processed/gold_cleaned.csv